/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TutorId = IDL.Nat;
export const UnlockStatus = IDL.Record({
  'freeUnlocksUsed' : IDL.Nat,
  'hasFreeUnlock' : IDL.Bool,
  'isUnlocked' : IDL.Bool,
});
export const CreateBookingRequest = IDL.Record({
  'date' : IDL.Text,
  'studentPhone' : IDL.Text,
  'tutorId' : TutorId,
  'timeSlot' : IDL.Text,
});
export const BookingId = IDL.Nat;
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : BookingId,
  'studentId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'studentPhone' : IDL.Text,
  'tutorId' : TutorId,
  'timeSlot' : IDL.Text,
});
export const ReviewId = IDL.Nat;
export const Review = IDL.Record({
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'reviewerId' : UserId,
  'comment' : IDL.Text,
  'tutorId' : TutorId,
  'rating' : IDL.Nat,
});
export const Tutor = IDL.Record({
  'id' : TutorId,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'pricePerHour' : IDL.Nat,
  'email' : IDL.Text,
  'imageUrl' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'distanceKm' : IDL.Float64,
  'isVerified' : IDL.Bool,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'reviewCount' : IDL.Nat,
});
export const LearningMode = IDL.Variant({
  'goToTutor' : IDL.Null,
  'learnAtHome' : IDL.Null,
});
export const TutorFilter = IDL.Record({
  'subjects' : IDL.Opt(IDL.Vec(IDL.Text)),
  'mode' : IDL.Opt(LearningMode),
  'location' : IDL.Opt(IDL.Text),
  'maxBudget' : IDL.Opt(IDL.Nat),
});
export const SubmitReviewRequest = IDL.Record({
  'comment' : IDL.Text,
  'tutorId' : TutorId,
  'rating' : IDL.Nat,
});
export const UnlockResult = IDL.Variant({
  'alreadyUnlocked' : IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text }),
  'success' : IDL.Record({
    'email' : IDL.Text,
    'usedFreeUnlock' : IDL.Bool,
    'phone' : IDL.Text,
  }),
  'noFreeUnlockAvailable' : IDL.Null,
});

export const idlService = IDL.Service({
  'checkUnlockStatus' : IDL.Func([TutorId], [UnlockStatus], ['query']),
  'createBooking' : IDL.Func([CreateBookingRequest], [Booking], []),
  'getBookings' : IDL.Func([UserId], [IDL.Vec(Booking)], ['query']),
  'getReviews' : IDL.Func([TutorId], [IDL.Vec(Review)], ['query']),
  'getTutorById' : IDL.Func([TutorId], [IDL.Opt(Tutor)], ['query']),
  'getTutors' : IDL.Func([IDL.Opt(TutorFilter)], [IDL.Vec(Tutor)], ['query']),
  'submitReview' : IDL.Func([SubmitReviewRequest], [Review], []),
  'unlockContact' : IDL.Func([TutorId], [UnlockResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TutorId = IDL.Nat;
  const UnlockStatus = IDL.Record({
    'freeUnlocksUsed' : IDL.Nat,
    'hasFreeUnlock' : IDL.Bool,
    'isUnlocked' : IDL.Bool,
  });
  const CreateBookingRequest = IDL.Record({
    'date' : IDL.Text,
    'studentPhone' : IDL.Text,
    'tutorId' : TutorId,
    'timeSlot' : IDL.Text,
  });
  const BookingId = IDL.Nat;
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : BookingId,
    'studentId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'studentPhone' : IDL.Text,
    'tutorId' : TutorId,
    'timeSlot' : IDL.Text,
  });
  const ReviewId = IDL.Nat;
  const Review = IDL.Record({
    'id' : ReviewId,
    'createdAt' : Timestamp,
    'reviewerId' : UserId,
    'comment' : IDL.Text,
    'tutorId' : TutorId,
    'rating' : IDL.Nat,
  });
  const Tutor = IDL.Record({
    'id' : TutorId,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'pricePerHour' : IDL.Nat,
    'email' : IDL.Text,
    'imageUrl' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'distanceKm' : IDL.Float64,
    'isVerified' : IDL.Bool,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'reviewCount' : IDL.Nat,
  });
  const LearningMode = IDL.Variant({
    'goToTutor' : IDL.Null,
    'learnAtHome' : IDL.Null,
  });
  const TutorFilter = IDL.Record({
    'subjects' : IDL.Opt(IDL.Vec(IDL.Text)),
    'mode' : IDL.Opt(LearningMode),
    'location' : IDL.Opt(IDL.Text),
    'maxBudget' : IDL.Opt(IDL.Nat),
  });
  const SubmitReviewRequest = IDL.Record({
    'comment' : IDL.Text,
    'tutorId' : TutorId,
    'rating' : IDL.Nat,
  });
  const UnlockResult = IDL.Variant({
    'alreadyUnlocked' : IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text }),
    'success' : IDL.Record({
      'email' : IDL.Text,
      'usedFreeUnlock' : IDL.Bool,
      'phone' : IDL.Text,
    }),
    'noFreeUnlockAvailable' : IDL.Null,
  });
  
  return IDL.Service({
    'checkUnlockStatus' : IDL.Func([TutorId], [UnlockStatus], ['query']),
    'createBooking' : IDL.Func([CreateBookingRequest], [Booking], []),
    'getBookings' : IDL.Func([UserId], [IDL.Vec(Booking)], ['query']),
    'getReviews' : IDL.Func([TutorId], [IDL.Vec(Review)], ['query']),
    'getTutorById' : IDL.Func([TutorId], [IDL.Opt(Tutor)], ['query']),
    'getTutors' : IDL.Func([IDL.Opt(TutorFilter)], [IDL.Vec(Tutor)], ['query']),
    'submitReview' : IDL.Func([SubmitReviewRequest], [Review], []),
    'unlockContact' : IDL.Func([TutorId], [UnlockResult], []),
  });
};

export const init = ({ IDL }) => { return []; };