/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'studentId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'studentPhone' : string,
  'tutorId' : TutorId,
  'timeSlot' : string,
}
export type BookingId = bigint;
export interface CreateBookingRequest {
  'date' : string,
  'studentPhone' : string,
  'tutorId' : TutorId,
  'timeSlot' : string,
}
export type LearningMode = { 'goToTutor' : null } |
  { 'learnAtHome' : null };
export interface Review {
  'id' : ReviewId,
  'createdAt' : Timestamp,
  'reviewerId' : UserId,
  'comment' : string,
  'tutorId' : TutorId,
  'rating' : bigint,
}
export type ReviewId = bigint;
export interface SubmitReviewRequest {
  'comment' : string,
  'tutorId' : TutorId,
  'rating' : bigint,
}
export type Timestamp = bigint;
export interface Tutor {
  'id' : TutorId,
  'subjects' : Array<string>,
  'name' : string,
  'pricePerHour' : bigint,
  'email' : string,
  'imageUrl' : string,
  'experienceYears' : bigint,
  'distanceKm' : number,
  'isVerified' : boolean,
  'rating' : number,
  'phone' : string,
  'reviewCount' : bigint,
}
export interface TutorFilter {
  'subjects' : [] | [Array<string>],
  'mode' : [] | [LearningMode],
  'location' : [] | [string],
  'maxBudget' : [] | [bigint],
}
export type TutorId = bigint;
export type UnlockResult = {
    'alreadyUnlocked' : { 'email' : string, 'phone' : string }
  } |
  {
    'success' : {
      'email' : string,
      'usedFreeUnlock' : boolean,
      'phone' : string,
    }
  } |
  { 'noFreeUnlockAvailable' : null };
export interface UnlockStatus {
  'freeUnlocksUsed' : bigint,
  'hasFreeUnlock' : boolean,
  'isUnlocked' : boolean,
}
export type UserId = string;
export interface _SERVICE {
  'checkUnlockStatus' : ActorMethod<[TutorId], UnlockStatus>,
  'createBooking' : ActorMethod<[CreateBookingRequest], Booking>,
  'getBookings' : ActorMethod<[UserId], Array<Booking>>,
  'getReviews' : ActorMethod<[TutorId], Array<Review>>,
  'getTutorById' : ActorMethod<[TutorId], [] | [Tutor]>,
  'getTutors' : ActorMethod<[[] | [TutorFilter]], Array<Tutor>>,
  'submitReview' : ActorMethod<[SubmitReviewRequest], Review>,
  'unlockContact' : ActorMethod<[TutorId], UnlockResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];