/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type BookingId = bigint;
export type Timestamp = bigint;
export interface CreateBookingRequest {
    date: string;
    studentPhone: string;
    tutorId: TutorId;
    timeSlot: string;
}
export interface TutorFilter {
    subjects?: Array<string>;
    mode?: LearningMode;
    location?: string;
    maxBudget?: bigint;
}
export type TutorId = bigint;
export type UserId = string;
export interface Tutor {
    id: TutorId;
    subjects: Array<string>;
    name: string;
    pricePerHour: bigint;
    email: string;
    imageUrl: string;
    experienceYears: bigint;
    distanceKm: number;
    isVerified: boolean;
    rating: number;
    phone: string;
    reviewCount: bigint;
}
export type UnlockResult = {
    __kind__: "alreadyUnlocked";
    alreadyUnlocked: {
        email: string;
        phone: string;
    };
} | {
    __kind__: "success";
    success: {
        email: string;
        usedFreeUnlock: boolean;
        phone: string;
    };
} | {
    __kind__: "noFreeUnlockAvailable";
    noFreeUnlockAvailable: null;
};
export interface UnlockStatus {
    freeUnlocksUsed: bigint;
    hasFreeUnlock: boolean;
    isUnlocked: boolean;
}
export interface Booking {
    id: BookingId;
    studentId: UserId;
    date: string;
    createdAt: Timestamp;
    studentPhone: string;
    tutorId: TutorId;
    timeSlot: string;
}
export interface SubmitReviewRequest {
    comment: string;
    tutorId: TutorId;
    rating: bigint;
}
export type ReviewId = bigint;
export interface Review {
    id: ReviewId;
    createdAt: Timestamp;
    reviewerId: UserId;
    comment: string;
    tutorId: TutorId;
    rating: bigint;
}
export enum LearningMode {
    goToTutor = "goToTutor",
    learnAtHome = "learnAtHome"
}
export interface backendInterface {
    checkUnlockStatus(tutorId: TutorId): Promise<UnlockStatus>;
    createBooking(req: CreateBookingRequest): Promise<Booking>;
    getBookings(studentId: UserId): Promise<Array<Booking>>;
    getReviews(tutorId: TutorId): Promise<Array<Review>>;
    getTutorById(id: TutorId): Promise<Tutor | null>;
    getTutors(filter: TutorFilter | null): Promise<Array<Tutor>>;
    submitReview(req: SubmitReviewRequest): Promise<Review>;
    unlockContact(tutorId: TutorId): Promise<UnlockResult>;
}
import type { LearningMode as _LearningMode, Tutor as _Tutor, TutorFilter as _TutorFilter, UnlockResult as _UnlockResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkUnlockStatus(arg0: TutorId): Promise<UnlockStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.checkUnlockStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkUnlockStatus(arg0);
            return result;
        }
    }
    async createBooking(arg0: CreateBookingRequest): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async getBookings(arg0: UserId): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings(arg0);
            return result;
        }
    }
    async getReviews(arg0: TutorId): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getTutorById(arg0: TutorId): Promise<Tutor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutorById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutorById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTutors(arg0: TutorFilter | null): Promise<Array<Tutor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutors(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutors(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitReview(arg0: SubmitReviewRequest): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return result;
        }
    }
    async unlockContact(arg0: TutorId): Promise<UnlockResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockContact(arg0);
                return from_candid_UnlockResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockContact(arg0);
            return from_candid_UnlockResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_UnlockResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnlockResult): UnlockResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tutor]): Tutor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyUnlocked: {
        email: string;
        phone: string;
    };
} | {
    success: {
        email: string;
        usedFreeUnlock: boolean;
        phone: string;
    };
} | {
    noFreeUnlockAvailable: null;
}): {
    __kind__: "alreadyUnlocked";
    alreadyUnlocked: {
        email: string;
        phone: string;
    };
} | {
    __kind__: "success";
    success: {
        email: string;
        usedFreeUnlock: boolean;
        phone: string;
    };
} | {
    __kind__: "noFreeUnlockAvailable";
    noFreeUnlockAvailable: null;
} {
    return "alreadyUnlocked" in value ? {
        __kind__: "alreadyUnlocked",
        alreadyUnlocked: value.alreadyUnlocked
    } : "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "noFreeUnlockAvailable" in value ? {
        __kind__: "noFreeUnlockAvailable",
        noFreeUnlockAvailable: value.noFreeUnlockAvailable
    } : value;
}
function to_candid_LearningMode_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LearningMode): _LearningMode {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TutorFilter_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TutorFilter): _TutorFilter {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TutorFilter | null): [] | [_TutorFilter] {
    return value === null ? candid_none() : candid_some(to_candid_TutorFilter_n3(_uploadFile, _downloadFile, value));
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjects?: Array<string>;
    mode?: LearningMode;
    location?: string;
    maxBudget?: bigint;
}): {
    subjects: [] | [Array<string>];
    mode: [] | [_LearningMode];
    location: [] | [string];
    maxBudget: [] | [bigint];
} {
    return {
        subjects: value.subjects ? candid_some(value.subjects) : candid_none(),
        mode: value.mode ? candid_some(to_candid_LearningMode_n5(_uploadFile, _downloadFile, value.mode)) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        maxBudget: value.maxBudget ? candid_some(value.maxBudget) : candid_none()
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LearningMode): {
    goToTutor: null;
} | {
    learnAtHome: null;
} {
    return value == LearningMode.goToTutor ? {
        goToTutor: null
    } : value == LearningMode.learnAtHome ? {
        learnAtHome: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
